//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDataUploader.SR_VOM_Image {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_VOM_Image.WSImageSyncSoap")]
    public interface WSImageSyncSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVomPhoto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVomPhoto(SSDataUploader.SR_VOM_Image.SysImage saveimage, string station);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SysImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imageIDField;
        
        private byte[] imageDataField;
        
        private bool activeField;
        
        private string createdByField;
        
        private System.DateTime createdOnField;
        
        private string modifiedByField;
        
        private System.DateTime modifiedOnField;
        
        private string lastActionField;
        
        private string imageRecordTypeField;
        
        private string imagestrField;
        
        private string passengerIdField;
        
        private System.Nullable<System.DateTime> uploadedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ImageID {
            get {
                return this.imageIDField;
            }
            set {
                this.imageIDField = value;
                this.RaisePropertyChanged("ImageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] ImageData {
            get {
                return this.imageDataField;
            }
            set {
                this.imageDataField = value;
                this.RaisePropertyChanged("ImageData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LastAction {
            get {
                return this.lastActionField;
            }
            set {
                this.lastActionField = value;
                this.RaisePropertyChanged("LastAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ImageRecordType {
            get {
                return this.imageRecordTypeField;
            }
            set {
                this.imageRecordTypeField = value;
                this.RaisePropertyChanged("ImageRecordType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Imagestr {
            get {
                return this.imagestrField;
            }
            set {
                this.imagestrField = value;
                this.RaisePropertyChanged("Imagestr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PassengerId {
            get {
                return this.passengerIdField;
            }
            set {
                this.passengerIdField = value;
                this.RaisePropertyChanged("PassengerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> UploadedOn {
            get {
                return this.uploadedOnField;
            }
            set {
                this.uploadedOnField = value;
                this.RaisePropertyChanged("UploadedOn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSImageSyncSoapChannel : SSDataUploader.SR_VOM_Image.WSImageSyncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSImageSyncSoapClient : System.ServiceModel.ClientBase<SSDataUploader.SR_VOM_Image.WSImageSyncSoap>, SSDataUploader.SR_VOM_Image.WSImageSyncSoap {
        
        public WSImageSyncSoapClient() {
        }
        
        public WSImageSyncSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSImageSyncSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSImageSyncSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSImageSyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveVomPhoto(SSDataUploader.SR_VOM_Image.SysImage saveimage, string station) {
            return base.Channel.SaveVomPhoto(saveimage, station);
        }
    }
}
