#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDataReceiver.LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PP_Enrollment")]
	public partial class PP_EnrollmentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRef_Individual(Ref_Individual instance);
    partial void UpdateRef_Individual(Ref_Individual instance);
    partial void DeleteRef_Individual(Ref_Individual instance);
    #endregion
		
		public PP_EnrollmentDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PP_EnrollmentConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PP_EnrollmentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PP_EnrollmentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PP_EnrollmentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PP_EnrollmentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ref_Individual> Ref_Individuals
		{
			get
			{
				return this.GetTable<Ref_Individual>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ref_Individual")]
	public partial class Ref_Individual : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ref_PersonalId;
		
		private string _PersonalNo;
		
		private string _TokenNo;
		
		private string _ApplicationType;
		
		private string _FullName_MMR;
		
		private string _FullName_ENG;
		
		private string _OtherName;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private string _PlaceOfBirth;
		
		private string _Race;
		
		private string _Religion;
		
		private string _NIRC;
		
		private string _Sex;
		
		private string _Nation;
		
		private string _Height;
		
		private string _HairColor;
		
		private string _EyeColor;
		
		private string _DistinctMark;
		
		private string _Job;
		
		private string _Phone;
		
		private string _Email;
		
		private string _CurrentAddress;
		
		private string _PermanentAddress;
		
		private string _ForeignAgency;
		
		private string _MyanmarAgency;
		
		private string _PassportNo;
		
		private System.Nullable<System.DateTime> _PassportDateOfExpiry;
		
		private string _PassportIssuingState;
		
		private string _PassportMRZ1;
		
		private string _PassportMRZ2;
		
		private System.Nullable<System.DateTime> _DateOfJoinIn;
		
		private string _FatherName;
		
		private string _FatherNationality;
		
		private string _MotherName;
		
		private string _MotherNationality;
		
		private string _SpouseName;
		
		private string _SpouseNationality;
		
		private string _OfficerRemark;
		
		private string _LastAction;
		
		private string _Status;
		
		private bool _Active;
		
		private string _CreatedBy;
		
		private System.DateTime _CreatedOn;
		
		private string _ModifiedBy;
		
		private System.DateTime _ModifiedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRef_PersonalIdChanging(string value);
    partial void OnRef_PersonalIdChanged();
    partial void OnPersonalNoChanging(string value);
    partial void OnPersonalNoChanged();
    partial void OnTokenNoChanging(string value);
    partial void OnTokenNoChanged();
    partial void OnApplicationTypeChanging(string value);
    partial void OnApplicationTypeChanged();
    partial void OnFullName_MMRChanging(string value);
    partial void OnFullName_MMRChanged();
    partial void OnFullName_ENGChanging(string value);
    partial void OnFullName_ENGChanged();
    partial void OnOtherNameChanging(string value);
    partial void OnOtherNameChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnPlaceOfBirthChanging(string value);
    partial void OnPlaceOfBirthChanged();
    partial void OnRaceChanging(string value);
    partial void OnRaceChanged();
    partial void OnReligionChanging(string value);
    partial void OnReligionChanged();
    partial void OnNIRCChanging(string value);
    partial void OnNIRCChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnNationChanging(string value);
    partial void OnNationChanged();
    partial void OnHeightChanging(string value);
    partial void OnHeightChanged();
    partial void OnHairColorChanging(string value);
    partial void OnHairColorChanged();
    partial void OnEyeColorChanging(string value);
    partial void OnEyeColorChanged();
    partial void OnDistinctMarkChanging(string value);
    partial void OnDistinctMarkChanged();
    partial void OnJobChanging(string value);
    partial void OnJobChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCurrentAddressChanging(string value);
    partial void OnCurrentAddressChanged();
    partial void OnPermanentAddressChanging(string value);
    partial void OnPermanentAddressChanged();
    partial void OnForeignAgencyChanging(string value);
    partial void OnForeignAgencyChanged();
    partial void OnMyanmarAgencyChanging(string value);
    partial void OnMyanmarAgencyChanged();
    partial void OnPassportNoChanging(string value);
    partial void OnPassportNoChanged();
    partial void OnPassportDateOfExpiryChanging(System.Nullable<System.DateTime> value);
    partial void OnPassportDateOfExpiryChanged();
    partial void OnPassportIssuingStateChanging(string value);
    partial void OnPassportIssuingStateChanged();
    partial void OnPassportMRZ1Changing(string value);
    partial void OnPassportMRZ1Changed();
    partial void OnPassportMRZ2Changing(string value);
    partial void OnPassportMRZ2Changed();
    partial void OnDateOfJoinInChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfJoinInChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnFatherNationalityChanging(string value);
    partial void OnFatherNationalityChanged();
    partial void OnMotherNameChanging(string value);
    partial void OnMotherNameChanged();
    partial void OnMotherNationalityChanging(string value);
    partial void OnMotherNationalityChanged();
    partial void OnSpouseNameChanging(string value);
    partial void OnSpouseNameChanged();
    partial void OnSpouseNationalityChanging(string value);
    partial void OnSpouseNationalityChanged();
    partial void OnOfficerRemarkChanging(string value);
    partial void OnOfficerRemarkChanged();
    partial void OnLastActionChanging(string value);
    partial void OnLastActionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnModifiedOnChanging(System.DateTime value);
    partial void OnModifiedOnChanged();
    #endregion
		
		public Ref_Individual()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ref_PersonalId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ref_PersonalId
		{
			get
			{
				return this._Ref_PersonalId;
			}
			set
			{
				if ((this._Ref_PersonalId != value))
				{
					this.OnRef_PersonalIdChanging(value);
					this.SendPropertyChanging();
					this._Ref_PersonalId = value;
					this.SendPropertyChanged("Ref_PersonalId");
					this.OnRef_PersonalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalNo", DbType="NVarChar(50)")]
		public string PersonalNo
		{
			get
			{
				return this._PersonalNo;
			}
			set
			{
				if ((this._PersonalNo != value))
				{
					this.OnPersonalNoChanging(value);
					this.SendPropertyChanging();
					this._PersonalNo = value;
					this.SendPropertyChanged("PersonalNo");
					this.OnPersonalNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenNo", DbType="NVarChar(50)")]
		public string TokenNo
		{
			get
			{
				return this._TokenNo;
			}
			set
			{
				if ((this._TokenNo != value))
				{
					this.OnTokenNoChanging(value);
					this.SendPropertyChanging();
					this._TokenNo = value;
					this.SendPropertyChanged("TokenNo");
					this.OnTokenNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationType", DbType="NVarChar(50)")]
		public string ApplicationType
		{
			get
			{
				return this._ApplicationType;
			}
			set
			{
				if ((this._ApplicationType != value))
				{
					this.OnApplicationTypeChanging(value);
					this.SendPropertyChanging();
					this._ApplicationType = value;
					this.SendPropertyChanged("ApplicationType");
					this.OnApplicationTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName_MMR", DbType="NVarChar(250)")]
		public string FullName_MMR
		{
			get
			{
				return this._FullName_MMR;
			}
			set
			{
				if ((this._FullName_MMR != value))
				{
					this.OnFullName_MMRChanging(value);
					this.SendPropertyChanging();
					this._FullName_MMR = value;
					this.SendPropertyChanged("FullName_MMR");
					this.OnFullName_MMRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName_ENG", DbType="NVarChar(250)")]
		public string FullName_ENG
		{
			get
			{
				return this._FullName_ENG;
			}
			set
			{
				if ((this._FullName_ENG != value))
				{
					this.OnFullName_ENGChanging(value);
					this.SendPropertyChanging();
					this._FullName_ENG = value;
					this.SendPropertyChanged("FullName_ENG");
					this.OnFullName_ENGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherName", DbType="NVarChar(250)")]
		public string OtherName
		{
			get
			{
				return this._OtherName;
			}
			set
			{
				if ((this._OtherName != value))
				{
					this.OnOtherNameChanging(value);
					this.SendPropertyChanging();
					this._OtherName = value;
					this.SendPropertyChanged("OtherName");
					this.OnOtherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceOfBirth", DbType="NVarChar(500)")]
		public string PlaceOfBirth
		{
			get
			{
				return this._PlaceOfBirth;
			}
			set
			{
				if ((this._PlaceOfBirth != value))
				{
					this.OnPlaceOfBirthChanging(value);
					this.SendPropertyChanging();
					this._PlaceOfBirth = value;
					this.SendPropertyChanged("PlaceOfBirth");
					this.OnPlaceOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Race", DbType="NVarChar(250)")]
		public string Race
		{
			get
			{
				return this._Race;
			}
			set
			{
				if ((this._Race != value))
				{
					this.OnRaceChanging(value);
					this.SendPropertyChanging();
					this._Race = value;
					this.SendPropertyChanged("Race");
					this.OnRaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="NVarChar(50)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this.OnReligionChanging(value);
					this.SendPropertyChanging();
					this._Religion = value;
					this.SendPropertyChanged("Religion");
					this.OnReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIRC", DbType="NVarChar(50)")]
		public string NIRC
		{
			get
			{
				return this._NIRC;
			}
			set
			{
				if ((this._NIRC != value))
				{
					this.OnNIRCChanging(value);
					this.SendPropertyChanging();
					this._NIRC = value;
					this.SendPropertyChanged("NIRC");
					this.OnNIRCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nation", DbType="NVarChar(50)")]
		public string Nation
		{
			get
			{
				return this._Nation;
			}
			set
			{
				if ((this._Nation != value))
				{
					this.OnNationChanging(value);
					this.SendPropertyChanging();
					this._Nation = value;
					this.SendPropertyChanged("Nation");
					this.OnNationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="NVarChar(50)")]
		public string Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HairColor", DbType="NVarChar(50)")]
		public string HairColor
		{
			get
			{
				return this._HairColor;
			}
			set
			{
				if ((this._HairColor != value))
				{
					this.OnHairColorChanging(value);
					this.SendPropertyChanging();
					this._HairColor = value;
					this.SendPropertyChanged("HairColor");
					this.OnHairColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EyeColor", DbType="NVarChar(50)")]
		public string EyeColor
		{
			get
			{
				return this._EyeColor;
			}
			set
			{
				if ((this._EyeColor != value))
				{
					this.OnEyeColorChanging(value);
					this.SendPropertyChanging();
					this._EyeColor = value;
					this.SendPropertyChanged("EyeColor");
					this.OnEyeColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistinctMark", DbType="NVarChar(500)")]
		public string DistinctMark
		{
			get
			{
				return this._DistinctMark;
			}
			set
			{
				if ((this._DistinctMark != value))
				{
					this.OnDistinctMarkChanging(value);
					this.SendPropertyChanging();
					this._DistinctMark = value;
					this.SendPropertyChanged("DistinctMark");
					this.OnDistinctMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job", DbType="NVarChar(500)")]
		public string Job
		{
			get
			{
				return this._Job;
			}
			set
			{
				if ((this._Job != value))
				{
					this.OnJobChanging(value);
					this.SendPropertyChanging();
					this._Job = value;
					this.SendPropertyChanged("Job");
					this.OnJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(250)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAddress", DbType="NVarChar(1000)")]
		public string CurrentAddress
		{
			get
			{
				return this._CurrentAddress;
			}
			set
			{
				if ((this._CurrentAddress != value))
				{
					this.OnCurrentAddressChanging(value);
					this.SendPropertyChanging();
					this._CurrentAddress = value;
					this.SendPropertyChanged("CurrentAddress");
					this.OnCurrentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermanentAddress", DbType="NVarChar(1000)")]
		public string PermanentAddress
		{
			get
			{
				return this._PermanentAddress;
			}
			set
			{
				if ((this._PermanentAddress != value))
				{
					this.OnPermanentAddressChanging(value);
					this.SendPropertyChanging();
					this._PermanentAddress = value;
					this.SendPropertyChanged("PermanentAddress");
					this.OnPermanentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeignAgency", DbType="NVarChar(1000)")]
		public string ForeignAgency
		{
			get
			{
				return this._ForeignAgency;
			}
			set
			{
				if ((this._ForeignAgency != value))
				{
					this.OnForeignAgencyChanging(value);
					this.SendPropertyChanging();
					this._ForeignAgency = value;
					this.SendPropertyChanged("ForeignAgency");
					this.OnForeignAgencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MyanmarAgency", DbType="NVarChar(1000)")]
		public string MyanmarAgency
		{
			get
			{
				return this._MyanmarAgency;
			}
			set
			{
				if ((this._MyanmarAgency != value))
				{
					this.OnMyanmarAgencyChanging(value);
					this.SendPropertyChanging();
					this._MyanmarAgency = value;
					this.SendPropertyChanged("MyanmarAgency");
					this.OnMyanmarAgencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNo", DbType="NVarChar(50)")]
		public string PassportNo
		{
			get
			{
				return this._PassportNo;
			}
			set
			{
				if ((this._PassportNo != value))
				{
					this.OnPassportNoChanging(value);
					this.SendPropertyChanging();
					this._PassportNo = value;
					this.SendPropertyChanged("PassportNo");
					this.OnPassportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportDateOfExpiry", DbType="Date")]
		public System.Nullable<System.DateTime> PassportDateOfExpiry
		{
			get
			{
				return this._PassportDateOfExpiry;
			}
			set
			{
				if ((this._PassportDateOfExpiry != value))
				{
					this.OnPassportDateOfExpiryChanging(value);
					this.SendPropertyChanging();
					this._PassportDateOfExpiry = value;
					this.SendPropertyChanged("PassportDateOfExpiry");
					this.OnPassportDateOfExpiryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportIssuingState", DbType="NVarChar(50)")]
		public string PassportIssuingState
		{
			get
			{
				return this._PassportIssuingState;
			}
			set
			{
				if ((this._PassportIssuingState != value))
				{
					this.OnPassportIssuingStateChanging(value);
					this.SendPropertyChanging();
					this._PassportIssuingState = value;
					this.SendPropertyChanged("PassportIssuingState");
					this.OnPassportIssuingStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportMRZ1", DbType="NVarChar(50)")]
		public string PassportMRZ1
		{
			get
			{
				return this._PassportMRZ1;
			}
			set
			{
				if ((this._PassportMRZ1 != value))
				{
					this.OnPassportMRZ1Changing(value);
					this.SendPropertyChanging();
					this._PassportMRZ1 = value;
					this.SendPropertyChanged("PassportMRZ1");
					this.OnPassportMRZ1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportMRZ2", DbType="NVarChar(50)")]
		public string PassportMRZ2
		{
			get
			{
				return this._PassportMRZ2;
			}
			set
			{
				if ((this._PassportMRZ2 != value))
				{
					this.OnPassportMRZ2Changing(value);
					this.SendPropertyChanging();
					this._PassportMRZ2 = value;
					this.SendPropertyChanged("PassportMRZ2");
					this.OnPassportMRZ2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfJoinIn", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfJoinIn
		{
			get
			{
				return this._DateOfJoinIn;
			}
			set
			{
				if ((this._DateOfJoinIn != value))
				{
					this.OnDateOfJoinInChanging(value);
					this.SendPropertyChanging();
					this._DateOfJoinIn = value;
					this.SendPropertyChanged("DateOfJoinIn");
					this.OnDateOfJoinInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(250)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherNationality", DbType="NVarChar(50)")]
		public string FatherNationality
		{
			get
			{
				return this._FatherNationality;
			}
			set
			{
				if ((this._FatherNationality != value))
				{
					this.OnFatherNationalityChanging(value);
					this.SendPropertyChanging();
					this._FatherNationality = value;
					this.SendPropertyChanged("FatherNationality");
					this.OnFatherNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="NVarChar(250)")]
		public string MotherName
		{
			get
			{
				return this._MotherName;
			}
			set
			{
				if ((this._MotherName != value))
				{
					this.OnMotherNameChanging(value);
					this.SendPropertyChanging();
					this._MotherName = value;
					this.SendPropertyChanged("MotherName");
					this.OnMotherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherNationality", DbType="NVarChar(50)")]
		public string MotherNationality
		{
			get
			{
				return this._MotherNationality;
			}
			set
			{
				if ((this._MotherNationality != value))
				{
					this.OnMotherNationalityChanging(value);
					this.SendPropertyChanging();
					this._MotherNationality = value;
					this.SendPropertyChanged("MotherNationality");
					this.OnMotherNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseName", DbType="NVarChar(250)")]
		public string SpouseName
		{
			get
			{
				return this._SpouseName;
			}
			set
			{
				if ((this._SpouseName != value))
				{
					this.OnSpouseNameChanging(value);
					this.SendPropertyChanging();
					this._SpouseName = value;
					this.SendPropertyChanged("SpouseName");
					this.OnSpouseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseNationality", DbType="NVarChar(50)")]
		public string SpouseNationality
		{
			get
			{
				return this._SpouseNationality;
			}
			set
			{
				if ((this._SpouseNationality != value))
				{
					this.OnSpouseNationalityChanging(value);
					this.SendPropertyChanging();
					this._SpouseNationality = value;
					this.SendPropertyChanged("SpouseNationality");
					this.OnSpouseNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficerRemark", DbType="NVarChar(1000)")]
		public string OfficerRemark
		{
			get
			{
				return this._OfficerRemark;
			}
			set
			{
				if ((this._OfficerRemark != value))
				{
					this.OnOfficerRemarkChanging(value);
					this.SendPropertyChanging();
					this._OfficerRemark = value;
					this.SendPropertyChanged("OfficerRemark");
					this.OnOfficerRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastAction", DbType="NVarChar(50)")]
		public string LastAction
		{
			get
			{
				return this._LastAction;
			}
			set
			{
				if ((this._LastAction != value))
				{
					this.OnLastActionChanging(value);
					this.SendPropertyChanging();
					this._LastAction = value;
					this.SendPropertyChanged("LastAction");
					this.OnLastActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime NOT NULL")]
		public System.DateTime ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
