<?xml version="1.0" encoding="utf-8"?><Database Name="PP_Enrollment" Class="PP_EnrollmentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.1.4.17;Initial Catalog=PP_Enrollment;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PP_EnrollmentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ref_Individual" Member="Ref_Individuals">
    <Type Name="Ref_Individual">
      <Column Name="Ref_PersonalId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonalNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TokenNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApplicationType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName_MMR" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FullName_ENG" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OtherName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PlaceOfBirth" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Race" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Religion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NIRC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Height" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HairColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EyeColor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DistinctMark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Job" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CurrentAddress" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PermanentAddress" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ForeignAgency" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MyanmarAgency" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PassportNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassportDateOfExpiry" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PassportIssuingState" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassportMRZ1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PassportMRZ2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfJoinIn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FatherNationality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MotherName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MotherNationality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SpouseName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SpouseNationality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OfficerRemark" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>