//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDataUploader.SR_VOM_Data {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_VOM_Data.WSDataSyncSoap")]
    public interface WSDataSyncSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVomData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVomData(SSDataUploader.SR_VOM_Data.Ref_Individual individual, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVomPersonInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVomPersonInfo(SSDataUploader.SR_VOM_Data.PersonInfo person, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVomRef_Passport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVomRef_Passport(SSDataUploader.SR_VOM_Data.Ref_Passport passport, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVom_BlackListHit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVom_BlackListHit(SSDataUploader.SR_VOM_Data.BlackListHit blackList, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVom_PrintSlip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVom_PrintSlip(SSDataUploader.SR_VOM_Data.Print_Slip printSlip, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVom_PrintVisaInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVom_PrintVisaInfo(SSDataUploader.SR_VOM_Data.Print_VisaInfo PrintVisaInfo, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVom_BlackList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVom_BlackList(SSDataUploader.SR_VOM_Data.Ref_Blacklist BlackList, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVom_Children", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVom_Children(SSDataUploader.SR_VOM_Data.Ref_Children Children, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVom_Slip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVom_Slip(SSDataUploader.SR_VOM_Data.Ref_Slip slip, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveVom_VisaDestroy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveVom_VisaDestroy(SSDataUploader.SR_VOM_Data.VisaDestroy visadestroy, string station);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ref_Individual : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ref_IndividualIdField;
        
        private string slipNoField;
        
        private string visitPurposeField;
        
        private string visaValidityField;
        
        private string typeOfBusinessField;
        
        private string companyNameField;
        
        private string recommendMinistryField;
        
        private System.Nullable<System.DateTime> visaDateOfIssueField;
        
        private System.Nullable<System.DateTime> visaDateOfExpiryField;
        
        private string visaNoField;
        
        private System.Nullable<int> visaFeeField;
        
        private string currencyField;
        
        private string visaTypeField;
        
        private string entriesField;
        
        private string visaNameField;
        
        private string placeOfIssueField;
        
        private string annotationField;
        
        private System.Nullable<int> staydaysField;
        
        private string visaCodeField;
        
        private string remarkField;
        
        private string counterNoField;
        
        private System.Nullable<int> statusField;
        
        private System.Nullable<int> totalInfantField;
        
        private string visaMRZ1Field;
        
        private string visaMRZ2Field;
        
        private string watchListResultField;
        
        private System.Nullable<int> watchListPointField;
        
        private string blackListHitIdField;
        
        private string personIdField;
        
        private string ref_PassportIdField;
        
        private System.Nullable<bool> activeField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> createdOnField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private System.Nullable<System.DateTime> uploadedOnField;
        
        private System.Nullable<bool> isDestroyField;
        
        private System.Nullable<int> queueNoField;
        
        private System.Nullable<System.DateTime> appointmentDateField;
        
        private string approvedByField;
        
        private System.Nullable<System.DateTime> approvedOnField;
        
        private string collectedByField;
        
        private System.Nullable<System.DateTime> collectedOnField;
        
        private Print_VisaInfo[] print_VisaInfosField;
        
        private Ref_Children[] ref_ChildrensField;
        
        private Ref_Passport ref_PassportField;
        
        private PersonInfo personInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ref_IndividualId {
            get {
                return this.ref_IndividualIdField;
            }
            set {
                this.ref_IndividualIdField = value;
                this.RaisePropertyChanged("Ref_IndividualId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SlipNo {
            get {
                return this.slipNoField;
            }
            set {
                this.slipNoField = value;
                this.RaisePropertyChanged("SlipNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VisitPurpose {
            get {
                return this.visitPurposeField;
            }
            set {
                this.visitPurposeField = value;
                this.RaisePropertyChanged("VisitPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VisaValidity {
            get {
                return this.visaValidityField;
            }
            set {
                this.visaValidityField = value;
                this.RaisePropertyChanged("VisaValidity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TypeOfBusiness {
            get {
                return this.typeOfBusinessField;
            }
            set {
                this.typeOfBusinessField = value;
                this.RaisePropertyChanged("TypeOfBusiness");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RecommendMinistry {
            get {
                return this.recommendMinistryField;
            }
            set {
                this.recommendMinistryField = value;
                this.RaisePropertyChanged("RecommendMinistry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> VisaDateOfIssue {
            get {
                return this.visaDateOfIssueField;
            }
            set {
                this.visaDateOfIssueField = value;
                this.RaisePropertyChanged("VisaDateOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> VisaDateOfExpiry {
            get {
                return this.visaDateOfExpiryField;
            }
            set {
                this.visaDateOfExpiryField = value;
                this.RaisePropertyChanged("VisaDateOfExpiry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string VisaNo {
            get {
                return this.visaNoField;
            }
            set {
                this.visaNoField = value;
                this.RaisePropertyChanged("VisaNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> VisaFee {
            get {
                return this.visaFeeField;
            }
            set {
                this.visaFeeField = value;
                this.RaisePropertyChanged("VisaFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string VisaType {
            get {
                return this.visaTypeField;
            }
            set {
                this.visaTypeField = value;
                this.RaisePropertyChanged("VisaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
                this.RaisePropertyChanged("Entries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string VisaName {
            get {
                return this.visaNameField;
            }
            set {
                this.visaNameField = value;
                this.RaisePropertyChanged("VisaName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PlaceOfIssue {
            get {
                return this.placeOfIssueField;
            }
            set {
                this.placeOfIssueField = value;
                this.RaisePropertyChanged("PlaceOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Annotation {
            get {
                return this.annotationField;
            }
            set {
                this.annotationField = value;
                this.RaisePropertyChanged("Annotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> Staydays {
            get {
                return this.staydaysField;
            }
            set {
                this.staydaysField = value;
                this.RaisePropertyChanged("Staydays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string VisaCode {
            get {
                return this.visaCodeField;
            }
            set {
                this.visaCodeField = value;
                this.RaisePropertyChanged("VisaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string CounterNo {
            get {
                return this.counterNoField;
            }
            set {
                this.counterNoField = value;
                this.RaisePropertyChanged("CounterNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<int> TotalInfant {
            get {
                return this.totalInfantField;
            }
            set {
                this.totalInfantField = value;
                this.RaisePropertyChanged("TotalInfant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string VisaMRZ1 {
            get {
                return this.visaMRZ1Field;
            }
            set {
                this.visaMRZ1Field = value;
                this.RaisePropertyChanged("VisaMRZ1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string VisaMRZ2 {
            get {
                return this.visaMRZ2Field;
            }
            set {
                this.visaMRZ2Field = value;
                this.RaisePropertyChanged("VisaMRZ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string WatchListResult {
            get {
                return this.watchListResultField;
            }
            set {
                this.watchListResultField = value;
                this.RaisePropertyChanged("WatchListResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<int> WatchListPoint {
            get {
                return this.watchListPointField;
            }
            set {
                this.watchListPointField = value;
                this.RaisePropertyChanged("WatchListPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string BlackListHitId {
            get {
                return this.blackListHitIdField;
            }
            set {
                this.blackListHitIdField = value;
                this.RaisePropertyChanged("BlackListHitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("PersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Ref_PassportId {
            get {
                return this.ref_PassportIdField;
            }
            set {
                this.ref_PassportIdField = value;
                this.RaisePropertyChanged("Ref_PassportId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<System.DateTime> UploadedOn {
            get {
                return this.uploadedOnField;
            }
            set {
                this.uploadedOnField = value;
                this.RaisePropertyChanged("UploadedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<bool> isDestroy {
            get {
                return this.isDestroyField;
            }
            set {
                this.isDestroyField = value;
                this.RaisePropertyChanged("isDestroy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<int> QueueNo {
            get {
                return this.queueNoField;
            }
            set {
                this.queueNoField = value;
                this.RaisePropertyChanged("QueueNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<System.DateTime> AppointmentDate {
            get {
                return this.appointmentDateField;
            }
            set {
                this.appointmentDateField = value;
                this.RaisePropertyChanged("AppointmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
                this.RaisePropertyChanged("ApprovedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<System.DateTime> ApprovedOn {
            get {
                return this.approvedOnField;
            }
            set {
                this.approvedOnField = value;
                this.RaisePropertyChanged("ApprovedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string CollectedBy {
            get {
                return this.collectedByField;
            }
            set {
                this.collectedByField = value;
                this.RaisePropertyChanged("CollectedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public System.Nullable<System.DateTime> CollectedOn {
            get {
                return this.collectedOnField;
            }
            set {
                this.collectedOnField = value;
                this.RaisePropertyChanged("CollectedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=43)]
        public Print_VisaInfo[] Print_VisaInfos {
            get {
                return this.print_VisaInfosField;
            }
            set {
                this.print_VisaInfosField = value;
                this.RaisePropertyChanged("Print_VisaInfos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=44)]
        public Ref_Children[] Ref_Childrens {
            get {
                return this.ref_ChildrensField;
            }
            set {
                this.ref_ChildrensField = value;
                this.RaisePropertyChanged("Ref_Childrens");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public Ref_Passport Ref_Passport {
            get {
                return this.ref_PassportField;
            }
            set {
                this.ref_PassportField = value;
                this.RaisePropertyChanged("Ref_Passport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public PersonInfo PersonInfo {
            get {
                return this.personInfoField;
            }
            set {
                this.personInfoField = value;
                this.RaisePropertyChanged("PersonInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Print_VisaInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string print_VisaInfo_IDField;
        
        private string visaNoField;
        
        private string visaTypeField;
        
        private string printedByField;
        
        private System.DateTime printedOnField;
        
        private string ref_IndividualIdField;
        
        private Ref_Individual ref_IndividualField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Print_VisaInfo_ID {
            get {
                return this.print_VisaInfo_IDField;
            }
            set {
                this.print_VisaInfo_IDField = value;
                this.RaisePropertyChanged("Print_VisaInfo_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VisaNo {
            get {
                return this.visaNoField;
            }
            set {
                this.visaNoField = value;
                this.RaisePropertyChanged("VisaNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VisaType {
            get {
                return this.visaTypeField;
            }
            set {
                this.visaTypeField = value;
                this.RaisePropertyChanged("VisaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PrintedBy {
            get {
                return this.printedByField;
            }
            set {
                this.printedByField = value;
                this.RaisePropertyChanged("PrintedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime PrintedOn {
            get {
                return this.printedOnField;
            }
            set {
                this.printedOnField = value;
                this.RaisePropertyChanged("PrintedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Ref_IndividualId {
            get {
                return this.ref_IndividualIdField;
            }
            set {
                this.ref_IndividualIdField = value;
                this.RaisePropertyChanged("Ref_IndividualId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Ref_Individual Ref_Individual {
            get {
                return this.ref_IndividualField;
            }
            set {
                this.ref_IndividualField = value;
                this.RaisePropertyChanged("Ref_Individual");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VisaDestroy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string visaDestroyIdField;
        
        private string ref_IndividualIdField;
        
        private string slipNoField;
        
        private string mAddressField;
        
        private string mTelNoField;
        
        private string mEmailField;
        
        private string visitPurposeField;
        
        private string visaValidityField;
        
        private string typeOfBusinessField;
        
        private string companyNameField;
        
        private System.Nullable<System.DateTime> visaDateOfIssueField;
        
        private System.Nullable<System.DateTime> visaDateOfExpiryField;
        
        private string visaNoField;
        
        private System.Nullable<int> visaFeeField;
        
        private string currencyField;
        
        private string visaTypeField;
        
        private string entriesField;
        
        private string visaNameField;
        
        private string placeOfIssueField;
        
        private string annotationField;
        
        private System.Nullable<int> staydaysField;
        
        private string visaCodeField;
        
        private string remarkField;
        
        private string counterNoField;
        
        private System.Nullable<int> statusField;
        
        private System.Nullable<int> totalInfantField;
        
        private string visaMRZ1Field;
        
        private string visaMRZ2Field;
        
        private string blackListHitIdField;
        
        private string personIdField;
        
        private string ref_PassportIdField;
        
        private System.Nullable<bool> activeField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> createdOnField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VisaDestroyId {
            get {
                return this.visaDestroyIdField;
            }
            set {
                this.visaDestroyIdField = value;
                this.RaisePropertyChanged("VisaDestroyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ref_IndividualId {
            get {
                return this.ref_IndividualIdField;
            }
            set {
                this.ref_IndividualIdField = value;
                this.RaisePropertyChanged("Ref_IndividualId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SlipNo {
            get {
                return this.slipNoField;
            }
            set {
                this.slipNoField = value;
                this.RaisePropertyChanged("SlipNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MAddress {
            get {
                return this.mAddressField;
            }
            set {
                this.mAddressField = value;
                this.RaisePropertyChanged("MAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MTelNo {
            get {
                return this.mTelNoField;
            }
            set {
                this.mTelNoField = value;
                this.RaisePropertyChanged("MTelNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MEmail {
            get {
                return this.mEmailField;
            }
            set {
                this.mEmailField = value;
                this.RaisePropertyChanged("MEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string VisitPurpose {
            get {
                return this.visitPurposeField;
            }
            set {
                this.visitPurposeField = value;
                this.RaisePropertyChanged("VisitPurpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string VisaValidity {
            get {
                return this.visaValidityField;
            }
            set {
                this.visaValidityField = value;
                this.RaisePropertyChanged("VisaValidity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TypeOfBusiness {
            get {
                return this.typeOfBusinessField;
            }
            set {
                this.typeOfBusinessField = value;
                this.RaisePropertyChanged("TypeOfBusiness");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> VisaDateOfIssue {
            get {
                return this.visaDateOfIssueField;
            }
            set {
                this.visaDateOfIssueField = value;
                this.RaisePropertyChanged("VisaDateOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> VisaDateOfExpiry {
            get {
                return this.visaDateOfExpiryField;
            }
            set {
                this.visaDateOfExpiryField = value;
                this.RaisePropertyChanged("VisaDateOfExpiry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string VisaNo {
            get {
                return this.visaNoField;
            }
            set {
                this.visaNoField = value;
                this.RaisePropertyChanged("VisaNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> VisaFee {
            get {
                return this.visaFeeField;
            }
            set {
                this.visaFeeField = value;
                this.RaisePropertyChanged("VisaFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string VisaType {
            get {
                return this.visaTypeField;
            }
            set {
                this.visaTypeField = value;
                this.RaisePropertyChanged("VisaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
                this.RaisePropertyChanged("Entries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string VisaName {
            get {
                return this.visaNameField;
            }
            set {
                this.visaNameField = value;
                this.RaisePropertyChanged("VisaName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PlaceOfIssue {
            get {
                return this.placeOfIssueField;
            }
            set {
                this.placeOfIssueField = value;
                this.RaisePropertyChanged("PlaceOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Annotation {
            get {
                return this.annotationField;
            }
            set {
                this.annotationField = value;
                this.RaisePropertyChanged("Annotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> Staydays {
            get {
                return this.staydaysField;
            }
            set {
                this.staydaysField = value;
                this.RaisePropertyChanged("Staydays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string VisaCode {
            get {
                return this.visaCodeField;
            }
            set {
                this.visaCodeField = value;
                this.RaisePropertyChanged("VisaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CounterNo {
            get {
                return this.counterNoField;
            }
            set {
                this.counterNoField = value;
                this.RaisePropertyChanged("CounterNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<int> TotalInfant {
            get {
                return this.totalInfantField;
            }
            set {
                this.totalInfantField = value;
                this.RaisePropertyChanged("TotalInfant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string VisaMRZ1 {
            get {
                return this.visaMRZ1Field;
            }
            set {
                this.visaMRZ1Field = value;
                this.RaisePropertyChanged("VisaMRZ1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string VisaMRZ2 {
            get {
                return this.visaMRZ2Field;
            }
            set {
                this.visaMRZ2Field = value;
                this.RaisePropertyChanged("VisaMRZ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string BlackListHitId {
            get {
                return this.blackListHitIdField;
            }
            set {
                this.blackListHitIdField = value;
                this.RaisePropertyChanged("BlackListHitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("PersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Ref_PassportId {
            get {
                return this.ref_PassportIdField;
            }
            set {
                this.ref_PassportIdField = value;
                this.RaisePropertyChanged("Ref_PassportId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ref_Slip : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string slipIDField;
        
        private string queueNoField;
        
        private string slipNoField;
        
        private string ref_PersonalIdField;
        
        private System.Nullable<bool> printStatusField;
        
        private bool activeField;
        
        private string createdByField;
        
        private System.DateTime createdOnField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SlipID {
            get {
                return this.slipIDField;
            }
            set {
                this.slipIDField = value;
                this.RaisePropertyChanged("SlipID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string QueueNo {
            get {
                return this.queueNoField;
            }
            set {
                this.queueNoField = value;
                this.RaisePropertyChanged("QueueNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SlipNo {
            get {
                return this.slipNoField;
            }
            set {
                this.slipNoField = value;
                this.RaisePropertyChanged("SlipNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Ref_PersonalId {
            get {
                return this.ref_PersonalIdField;
            }
            set {
                this.ref_PersonalIdField = value;
                this.RaisePropertyChanged("Ref_PersonalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> PrintStatus {
            get {
                return this.printStatusField;
            }
            set {
                this.printStatusField = value;
                this.RaisePropertyChanged("PrintStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ref_Blacklist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string blacklistIDField;
        
        private string nameField;
        
        private string dOBField;
        
        private string sexField;
        
        private string pPNoField;
        
        private string nrcNoField;
        
        private string countryField;
        
        private string nationalityField;
        
        private string fatherNameField;
        
        private string motherNameField;
        
        private string addressField;
        
        private string letterNoField;
        
        private string reasonField;
        
        private string remarkField;
        
        private System.Nullable<bool> isDeletedField;
        
        private System.Nullable<bool> isExportedField;
        
        private System.Nullable<System.DateTime> createdOnField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private string modifiedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BlacklistID {
            get {
                return this.blacklistIDField;
            }
            set {
                this.blacklistIDField = value;
                this.RaisePropertyChanged("BlacklistID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PPNo {
            get {
                return this.pPNoField;
            }
            set {
                this.pPNoField = value;
                this.RaisePropertyChanged("PPNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NrcNo {
            get {
                return this.nrcNoField;
            }
            set {
                this.nrcNoField = value;
                this.RaisePropertyChanged("NrcNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
                this.RaisePropertyChanged("FatherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MotherName {
            get {
                return this.motherNameField;
            }
            set {
                this.motherNameField = value;
                this.RaisePropertyChanged("MotherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LetterNo {
            get {
                return this.letterNoField;
            }
            set {
                this.letterNoField = value;
                this.RaisePropertyChanged("LetterNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
                this.RaisePropertyChanged("IsDeleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> IsExported {
            get {
                return this.isExportedField;
            }
            set {
                this.isExportedField = value;
                this.RaisePropertyChanged("IsExported");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Print_Slip : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string printSlipIdField;
        
        private string slipNoField;
        
        private string nameField;
        
        private string sexField;
        
        private System.Nullable<System.DateTime> dateOfBirthField;
        
        private string passportNoField;
        
        private string nationalityField;
        
        private string visaNameField;
        
        private System.Nullable<int> visaFeeField;
        
        private bool activeField;
        
        private string createdByField;
        
        private System.DateTime createdOnField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PrintSlipId {
            get {
                return this.printSlipIdField;
            }
            set {
                this.printSlipIdField = value;
                this.RaisePropertyChanged("PrintSlipId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SlipNo {
            get {
                return this.slipNoField;
            }
            set {
                this.slipNoField = value;
                this.RaisePropertyChanged("SlipNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PassportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
                this.RaisePropertyChanged("PassportNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string VisaName {
            get {
                return this.visaNameField;
            }
            set {
                this.visaNameField = value;
                this.RaisePropertyChanged("VisaName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> VisaFee {
            get {
                return this.visaFeeField;
            }
            set {
                this.visaFeeField = value;
                this.RaisePropertyChanged("VisaFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BlackListHit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string blackListHitIdField;
        
        private string blackListIdField;
        
        private string refIndividualIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string dateOfBirthField;
        
        private string sexField;
        
        private string nationalityField;
        
        private string passportNoField;
        
        private string bLResultField;
        
        private System.Nullable<int> bLPointField;
        
        private System.DateTime hitOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BlackListHitId {
            get {
                return this.blackListHitIdField;
            }
            set {
                this.blackListHitIdField = value;
                this.RaisePropertyChanged("BlackListHitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BlackListId {
            get {
                return this.blackListIdField;
            }
            set {
                this.blackListIdField = value;
                this.RaisePropertyChanged("BlackListId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RefIndividualId {
            get {
                return this.refIndividualIdField;
            }
            set {
                this.refIndividualIdField = value;
                this.RaisePropertyChanged("RefIndividualId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PassportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
                this.RaisePropertyChanged("PassportNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BLResult {
            get {
                return this.bLResultField;
            }
            set {
                this.bLResultField = value;
                this.RaisePropertyChanged("BLResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> BLPoint {
            get {
                return this.bLPointField;
            }
            set {
                this.bLPointField = value;
                this.RaisePropertyChanged("BLPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime HitOn {
            get {
                return this.hitOnField;
            }
            set {
                this.hitOnField = value;
                this.RaisePropertyChanged("HitOn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string personIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string dOBField;
        
        private string nationalityField;
        
        private string sexField;
        
        private string occupationField;
        
        private string mAddressField;
        
        private string pAddressField;
        
        private string telNoField;
        
        private string emailField;
        
        private bool activeField;
        
        private string createdByField;
        
        private System.DateTime createdOnField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private Ref_Individual[] ref_IndividualsField;
        
        private Ref_Passport[] ref_PassportsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("PersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
                this.RaisePropertyChanged("Occupation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MAddress {
            get {
                return this.mAddressField;
            }
            set {
                this.mAddressField = value;
                this.RaisePropertyChanged("MAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PAddress {
            get {
                return this.pAddressField;
            }
            set {
                this.pAddressField = value;
                this.RaisePropertyChanged("PAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TelNo {
            get {
                return this.telNoField;
            }
            set {
                this.telNoField = value;
                this.RaisePropertyChanged("TelNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public Ref_Individual[] Ref_Individuals {
            get {
                return this.ref_IndividualsField;
            }
            set {
                this.ref_IndividualsField = value;
                this.RaisePropertyChanged("Ref_Individuals");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public Ref_Passport[] Ref_Passports {
            get {
                return this.ref_PassportsField;
            }
            set {
                this.ref_PassportsField = value;
                this.RaisePropertyChanged("Ref_Passports");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ref_Passport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ref_PassportIdField;
        
        private string passportTypeField;
        
        private string countryCodeField;
        
        private string passportNoField;
        
        private System.Nullable<System.DateTime> dateOfIssueField;
        
        private System.Nullable<System.DateTime> dateOfExpireField;
        
        private string mRZ1Field;
        
        private string mRZ2Field;
        
        private string mRZ3Field;
        
        private string personIdField;
        
        private bool activeField;
        
        private string createdByField;
        
        private System.DateTime createdOnField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private Ref_Individual[] ref_IndividualsField;
        
        private PersonInfo personInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ref_PassportId {
            get {
                return this.ref_PassportIdField;
            }
            set {
                this.ref_PassportIdField = value;
                this.RaisePropertyChanged("Ref_PassportId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassportType {
            get {
                return this.passportTypeField;
            }
            set {
                this.passportTypeField = value;
                this.RaisePropertyChanged("PassportType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PassportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
                this.RaisePropertyChanged("PassportNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> DateOfIssue {
            get {
                return this.dateOfIssueField;
            }
            set {
                this.dateOfIssueField = value;
                this.RaisePropertyChanged("DateOfIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> DateOfExpire {
            get {
                return this.dateOfExpireField;
            }
            set {
                this.dateOfExpireField = value;
                this.RaisePropertyChanged("DateOfExpire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MRZ1 {
            get {
                return this.mRZ1Field;
            }
            set {
                this.mRZ1Field = value;
                this.RaisePropertyChanged("MRZ1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MRZ2 {
            get {
                return this.mRZ2Field;
            }
            set {
                this.mRZ2Field = value;
                this.RaisePropertyChanged("MRZ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MRZ3 {
            get {
                return this.mRZ3Field;
            }
            set {
                this.mRZ3Field = value;
                this.RaisePropertyChanged("MRZ3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("PersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public Ref_Individual[] Ref_Individuals {
            get {
                return this.ref_IndividualsField;
            }
            set {
                this.ref_IndividualsField = value;
                this.RaisePropertyChanged("Ref_Individuals");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public PersonInfo PersonInfo {
            get {
                return this.personInfoField;
            }
            set {
                this.personInfoField = value;
                this.RaisePropertyChanged("PersonInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ref_Children : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ref_ChildlIdField;
        
        private string ref_IndividualIdField;
        
        private string fullNameField;
        
        private string genderField;
        
        private System.Nullable<System.DateTime> dateOfBirthField;
        
        private string typeField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> createdOnField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> modifiedOnField;
        
        private System.Nullable<bool> activeField;
        
        private Ref_Individual ref_IndividualField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ref_ChildlId {
            get {
                return this.ref_ChildlIdField;
            }
            set {
                this.ref_ChildlIdField = value;
                this.RaisePropertyChanged("Ref_ChildlId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ref_IndividualId {
            get {
                return this.ref_IndividualIdField;
            }
            set {
                this.ref_IndividualIdField = value;
                this.RaisePropertyChanged("Ref_IndividualId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> CreatedOn {
            get {
                return this.createdOnField;
            }
            set {
                this.createdOnField = value;
                this.RaisePropertyChanged("CreatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
                this.RaisePropertyChanged("ModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.modifiedOnField;
            }
            set {
                this.modifiedOnField = value;
                this.RaisePropertyChanged("ModifiedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Ref_Individual Ref_Individual {
            get {
                return this.ref_IndividualField;
            }
            set {
                this.ref_IndividualField = value;
                this.RaisePropertyChanged("Ref_Individual");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDataSyncSoapChannel : SSDataUploader.SR_VOM_Data.WSDataSyncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDataSyncSoapClient : System.ServiceModel.ClientBase<SSDataUploader.SR_VOM_Data.WSDataSyncSoap>, SSDataUploader.SR_VOM_Data.WSDataSyncSoap {
        
        public WSDataSyncSoapClient() {
        }
        
        public WSDataSyncSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDataSyncSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDataSyncSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDataSyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string SaveVomData(SSDataUploader.SR_VOM_Data.Ref_Individual individual, string station) {
            return base.Channel.SaveVomData(individual, station);
        }
        
        public string SaveVomPersonInfo(SSDataUploader.SR_VOM_Data.PersonInfo person, string station) {
            return base.Channel.SaveVomPersonInfo(person, station);
        }
        
        public string SaveVomRef_Passport(SSDataUploader.SR_VOM_Data.Ref_Passport passport, string station) {
            return base.Channel.SaveVomRef_Passport(passport, station);
        }
        
        public string SaveVom_BlackListHit(SSDataUploader.SR_VOM_Data.BlackListHit blackList, string station) {
            return base.Channel.SaveVom_BlackListHit(blackList, station);
        }
        
        public string SaveVom_PrintSlip(SSDataUploader.SR_VOM_Data.Print_Slip printSlip, string station) {
            return base.Channel.SaveVom_PrintSlip(printSlip, station);
        }
        
        public string SaveVom_PrintVisaInfo(SSDataUploader.SR_VOM_Data.Print_VisaInfo PrintVisaInfo, string station) {
            return base.Channel.SaveVom_PrintVisaInfo(PrintVisaInfo, station);
        }
        
        public string SaveVom_BlackList(SSDataUploader.SR_VOM_Data.Ref_Blacklist BlackList, string station) {
            return base.Channel.SaveVom_BlackList(BlackList, station);
        }
        
        public string SaveVom_Children(SSDataUploader.SR_VOM_Data.Ref_Children Children, string station) {
            return base.Channel.SaveVom_Children(Children, station);
        }
        
        public string SaveVom_Slip(SSDataUploader.SR_VOM_Data.Ref_Slip slip, string station) {
            return base.Channel.SaveVom_Slip(slip, station);
        }
        
        public string SaveVom_VisaDestroy(SSDataUploader.SR_VOM_Data.VisaDestroy visadestroy, string station) {
            return base.Channel.SaveVom_VisaDestroy(visadestroy, station);
        }
    }
}
